### ISSUE TITLE
Tools selection

### ISSUE THREAD

**Issue by L00159024** [ruthlennonatu/bsc23_season#62]
As a team of developers it would be best if we could find tools that could be used throughout the pipeline that suits everyone's skill level that's also compatible with the language and project requirements.

**Comment by MalachyJohnMc** [comment]
We have decided on the following tools:

Security: OWASP ZAP, CodeQL, Solarscan
Automation: Maven, Selenium
Code QA Testing: JUnit Tests
Documentation: JavaDoc
Performance: Jmeter
Project Management Tool: Github Projects
Code Coverage: Code Coverage

**Comment by MalachyJohnMc** [comment]
Closed based on our tools having been selected for the pipeline.
